version: '3.8'
services:
  web:
    container_name: web
    build: .
    env_file:
      - .env.dev
    environment:
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DIALECT: ${DB_DIALECT}
      DATABASE_URL: ${DB_DIALECT}://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_DATABASE}
      USE_SSL: ${USE_SSL}
      DB_SSL_REQUIRE: ${DB_SSL_REQUIRE}
      DB_SSL_REJECT_UNAUTHORIZED: ${DB_SSL_REJECT_UNAUTHORIZED}
      OPTION_ALLOW_NEW_REGISTRATIONS: ${OPTION_ALLOW_NEW_REGISTRATIONS}
      # SMTP_AUTH_PASS: ${SMTP_AUTH_PASS}
      # SMTP_AUTH_USER: ${SMTP_AUTH_USER}
      # SMTP_FROM: ${SMTP_FROM}
      SMTP_HOST: ${SMTP_HOST}
      # SMTP_PORT: ${SMTP_PORT}
      # SMTP_REQUIRE_TLS: ${SMTP_REQUIRE_TLS}
    ports:
      - "3000:3000"
    # volumes:
    #   - ./config:/app/config
    restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env.dev
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dev-pgsql:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

  # mysql:
  #   image: mysql:latest
  #   container_name: mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
  #     MYSQL_DATABASE: ${DB_DATABASE}
  #     MYSQL_USER: ${DB_USER}
  #     MYSQL_PASSWORD: ${DB_PASSWORD}
  #     MYSQL_ROOT_HOST: '%'
  #   volumes:
  #     - my-mysql-data:/var/lib/mysql
  #   ports:
  #     - "${DB_PORT}:3306"
  #   command: --default-authentication-plugin=mysql_native_password

  # admin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: admin
  #   environment:
  #     PMA_HOST: ${DB_HOST}
  #     PMA_PORT: ${DB_PORT}
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - mysql

volumes:
#   my-mysql-data:
  dev-pgsql:
